### ISSUE TITLE
Intermittent crashing 

### ISSUE THREAD

**Issue by guymuff** [dfellis/queue-flow#12] opened 2013-09-10 22:01 UTC
Hello.  I just started working with queue-flow.  I'm seeing intermittent failures that the trycatch module can't seem to catch resulting in server crashes.  I'm wondering if the following stacktrace rings any bells?  Any reason why this is not hitting the trycatch handlers?

/Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/queue-flow/lib/queue-flow.js:160
        Array.prototype.push.apply(queue, values);
                             ^
TypeError: Array.prototype.push called on null or undefined
    at Q.push (/Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/queue-flow/lib/queue-flow.js:160:30)
    at /Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/queue-flow/lib/queue-flow.js:558:22
    at handlerCallback (/Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/queue-flow/lib/queue-flow.js:135:9)
    at Q.ercb (/Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/queue-flow/lib/queue-flow.js:557:9)
    at /Users/guy.muff/source/local/cmdline/email/aws-eb-server/imported/parser/src/Datastore.js:188:7
    at /Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/underscore/underscore.js:724:19
    at /Users/guy.muff/source/local/cmdline/email/aws-eb-server/imported/common/src/aws/aws-sdk.js:87:41
    at /Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/queue-flow/lib/queue-flow.js:259:17
    at handlerCall (/Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/queue-flow/lib/queue-flow.js:128:9)
    at handlerCallback (/Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/queue-flow/lib/queue-flow.js:142:17)

**Comment by dfellis** [comment] 2013-09-10 22:25
That sort of failure could only happen if the `queue` object was no longer an array but was converted to `null`, which happens when the queue is being closed.

I've never had it happen to me, before, but I have a guess on how you're triggering it. Something like:

``` js
var myQueue = q([1, 2, 3, 4, 5]).map(...

...

myQueue.push(23, 24, 25);
```

Are you doing anything like that?

In any case, the push functions should either:
1. Guard against this when the queue has already been closed.
2. Replace them with no-op functions (since the queue has already closed).

**Comment by dfellis** [comment] 2013-09-11 05:59
So this is the test I created that fails in the latest version of queue-flow:

``` js
exports.pushToClosedQueue = function(test) {
    bootstrap(test);
    test.expect(1);
    var deadQueue = q([1, 2, 3]).map(function(val) { return val*2; });
    deadQueue.close();
    test.doesNotThrow(function() {
        deadQueue.push(4, 5, 6);
    });
    test.done();
};
```

I've also written a fix so this test will pass, but... maybe it shouldn't pass? Anything `push`ed into a queue that has this crash has already closed, so anything you push in now won't actually be processed. 99% of the time, that would be considered a bug and silently eating the data would be bad.

So, this is what I'm thinking of doing, instead:

``` js
exports.pushToClosedQueue = function(test) {
    bootstrap(test);
    test.expect(1);
    var deadQueue = q([1, 2, 3]).map(function(val) { return val*2; });
    deadQueue.close();
    test.throws(function() {
        deadQueue.push(4, 5, 6);
    }, /Queue already closed/);
    test.done();
};
```

I'm perfectly willing to help you debug the issue you're having with the queue(s) closing themselves before you expect them too, though, if you want to post some sample of how you're using queue-flow?

**Comment by gmp** [comment] 2013-10-04 01:54
Hey @dfellis, I'm working with @guymuff on this issue and here's some more context to what we're doing and where the error could be occuring:

``` javascript
function scanAll (tableName, callback) {
  var that = this;
  var items = [];

  var handleError = _(function (err) {
    callback(err);
  }).once();

  q('end')
    .each(function () { _.once(callback)(null, items); });

  q('recursiveScan')
    .node(function (exclusiveStartKey, cb) {
      var query = { TableName: tableName };
      if (exclusiveStartKey) query.exclusiveStartKey = exclusiveStartKey;
      that.scan(query, _(cb).once());
    }, handleError)
    .map(function (data) { // Extract Items and return the last key that was scanned.
      if (!data || !data.Items || !data.Items.length)
        return null;

      items = items.concat(data.Items);
      return data.LastEvaluatedKey;
    })
    .branch(function (lastKey) {
      return lastKey ? 'recursiveScan' : 'end';
    });

  q([null]).branch('recursiveScan');
}
```

Looking at the stack trace in the initial issue comment, aws-sdk.js:87 is the each method in the 'end' branch.

Maybe you can see something blatantly wrong with the way we're using queue-flow in the above code?

**Comment by dfellis** [comment] 2013-10-04 15:08
Based on what you've told me; the error is _not_ in this code, then. It's in the `callback`.

`at /Users/guy.muff/source/local/cmdline/email/aws-eb-server/imported/common/src/aws/aws-sdk.js:87:41`
Run the `each` function for the `end` queue. Since it's not failing here, this code is succeeding (as expected).

`at /Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/underscore/underscore.js:724:19`
Run underscore's `once` function on the callback

`at /Users/guy.muff/source/local/cmdline/email/aws-eb-server/imported/parser/src/Datastore.js:188:7`
Run the callback function

`at Q.ercb (/Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/queue-flow/lib/queue-flow.js:557:9)`
The callback is returning into a `node` or `exec` call

`at handlerCallback (/Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/queue-flow/lib/queue-flow.js:135:9)`
The result is being enqueued to be pushed into the next step

`at /Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/queue-flow/lib/queue-flow.js:558:22`
Pushing the result into the next step

`at Q.push (/Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/queue-flow/lib/queue-flow.js:160:30)`
The next step is receiving the data

```
/Users/guy.muff/source/local/cmdline/email/aws-eb-server/node_modules/queue-flow/lib/queue-flow.js:160
Array.prototype.push.apply(queue, values);
^
TypeError: Array.prototype.push called on null or undefined
```

The next step was already closed, so this fails.

To make sure it's perfectly clear, queues started this way:

`q('someQueue')`

stay open until you `q('someQueue').close()` or `q('someQueue').kill()` them. But queues started this way:

`q([1, 2, 3, 4])...`

automatically close once they finish processing the data they've been provided (so you don't have zombie objects sitting in memory after the code has finished). This may be what's tripping up the other bit of code that's failing.

**Comment by gmp** [comment] 2013-10-11 03:48
I've been trying to reproduce this crash for a bit now and can't seem to do it without blatantly closing the queue. Going to run a couple more stress tests using the fix from #13 and if all is well, we can likely assume this to be closed.

**Comment by gmp** [comment] 2013-10-14 21:35
After testing over the weekend, I think we're good to close this. Will reopen if anything happens to come up again.

Thanks again for all your help and responsiveness!

**Comment by dfellis** [comment] 2013-10-14 21:44
:thumbsup:

**Closed as completed by dfellis** 2013-10-14 21:44 UTC
